language: java
sudo: required
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.sonar
  - $HOME/.m2
  
addons:
  hosts:
    - api-itest.metaform.fi
  apt:
    packages:
      - oracle-java8-installer
  sonarcloud:
    organization: "metatavu-oy"
          
install: true
  
before_script:
  - scripts/start-keycloak.sh
  
script:
  - . travis.sh

notifications:
  email: false
  webhooks:
    - http://travis.metatavu.io:7333/travisping