language: java
sudo: required
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.sonar
  - $HOME/.m2
  
addons:
  apt:
    packages:
      - oracle-java8-installer
      
install: true

notifications:
  email: false
  webhooks:
- http://travis.metatavu.io:7333/travisping
