language: java
sudo: required
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.sonar
  - $HOME/.m2
  
addons:
  hosts:
    - api-itest.metaform.fi
  apt:
    packages:
      - oracle-java8-installer
  sonarcloud:
    organization: "metatavu-oy"

services:
  - postgresql

install: true
  
before_script:
  - scripts/start-keycloak.sh
  - psql -c 'create database mftest' -U postgres
  - psql -c 'create user mftest' -U postgres
  - psql -c "alter user mftest with password 'mftest'"
  - psql -c "alter role mftest with login"

script:
  - . travis.sh

notifications:
  email: false
  webhooks:
    - http://travis.metatavu.io:7333/travisping
