version: "3"
services:  
  mysql:
    image: mysql:5.6
    command: [--lower_case_table_names=1,--max-allowed-packet=67108864]
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  api:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8081:8080"
      - "5005:5005"
    depends_on:
      - mysql
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql:3306/api?useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
      QUARKUS_DATASOURCE_PASSWORD: root
      QUARKUS_DATASOURCE_USERNAME: root
      METAFORM_UPLOADS_FOLDER: /tmp
      METAFORMS_KEYCLOAK_ADMIN_USER: admin
      METAFORMS_KEYCLOAK_ADMIN_PASSWORD: admin
      METAFORMS_KEYCLOAK_ADMIN_REALM: essote
      METAFORMS_KEYCLOAK_ADMIN_ADMIN_CLIENT_ID: metaform-api
      METAFORMS_KEYCLOAK_ADMIN_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      METAFORMS_KEYCLOAK_ADMIN_HOST: ${METAFORMS_KEYCLOAK_ADMIN_HOST}
      METAFORMS_KEYCLOAK_ADMIN_RESOURCESERVER: ${METAFORMS_KEYCLOAK_ADMIN_RESOURCESERVER}
      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloak:8080/auth
      QUARKUS_OIDC_CLIENT_ID: metaformapi
      QUARKUS_OIDC_CREDENTIALS_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      QUARKUS_OIDC_CONNECTION_DELAY: 60s
      MAILGUN_DOMAIN: mg.example.com
      MAILGUN_API_KEY: na
      MAILGUN_SENDER_EMAIL: noreply@mg.example.com
      MAILGUN_SENDER_NAME: example
      MAILGUN_API_URL: https://api.example.com/v3
      METAFORMS_KEYCLOAK_CARD_IDENTITY_PROVIDER: card
      CARD_AUTH_KEYCLOAK_ADMIN_REALM: essote
      CARD_AUTH_KEYCLOAK_ADMIN_ADMIN_CLIENT_ID: metaform-api
      CARD_AUTH_KEYCLOAK_ADMIN_SECRET: ${CARD_AUTH_KEYCLOAK_ADMIN_SECRET}
      CARD_AUTH_KEYCLOAK_ADMIN_USER: admin
      CARD_AUTH_KEYCLOAK_ADMIN_PASSWORD: admin
      CARD_AUTH_KEYCLOAK_ADMIN_HOST: http://keycloak:8080/auth
      METAFORM_PDF_RENDERER_URL: ${METAFORM_PDF_RENDERER_URL}
      METAFORM_PDF_RENDERER_APIKEY: ${METAFORM_PDF_RENDERER_APIKEY}
      RUNMODE: PRODUCTION
      JAVA_ENABLE_DEBUG: true
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    hostname: keycloak
    container_name: keycloak
    command: start-dev -Dsuspend
    ports:
      - "8080:8080"
    environment:
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak?useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KC_DB: mysql
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: /auth
volumes:
  db_data: {}