version: "3"
services:  
  mysql:
    image: mysql:5.6
    command: [--lower_case_table_names=1,--max-allowed-packet=67108864]
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  api:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 8081:8080
    depends_on:
      - mysql
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql:3306/api?useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
      QUARKUS_DATASOURCE_PASSWORD: root
      QUARKUS_DATASOURCE_USERNAME: root
      METAFORM_UPLOADS_FOLDER: /tmp
      METAFORMS_KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      METAFORMS_KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      METAFORMS_KEYCLOAK_ADMIN_REALM: ${KEYCLOAK_ADMIN_REALM}
      METAFORMS_KEYCLOAK_ADMIN_ADMIN_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      METAFORMS_KEYCLOAK_ADMIN_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      METAFORMS_KEYCLOAK_ADMIN_HOST: http://keycloak:8080/auth
      QUARKUS_OIDC_AUTH_SERVER_URL: ${QUARKUS_OIDC_AUTH_SERVER_URL}
      QUARKUS_OIDC_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      QUARKUS_OIDC_CREDENTIALS_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      QUARKUS_OIDC_CONNECTION_DELAY: 60s
      MAILGUN_DOMAIN: mg.example.com
      MAILGUN_API_KEY: na
      MAILGUN_SENDER_EMAIL: noreply@mg.example.com
      MAILGUN_SENDER_NAME: example
      MAILGUN_API_URL: https://api.example.com/v3
  keycloak:
    image: jboss/keycloak:4.5.0.Final
    hostname: keycloak
    container_name: keycloak
    ports:
      - 8080:8080
    volumes:
      - ./dev/:/opt/keycloak/
    environment:
      DB_VENDOR: mysql
      DB_DATABASE: keycloak
      DB_USER: root
      DB_ADDR: mysql
      DB_PASSWORD: root
      JDBC_PARAMS: useSSL=false&allowPublicKeyRetrieval=true
volumes:
  db_data: {}